chore: bring Lou's reworked commit msg (SCRUM-79)

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,13 +1,18 @@
-#!/bin/bash
-
+#!/bin/sh
 commit_message_file="$1"
-commit_message=$(head -n 1 "$commit_message_file") # Read only the first line
-valid_commit_regex='^([Rr]efactor|[Ff]eature|[Ff]eat|[Bb]ugfix|[Dd]ocs|[Cc]hore|[Bb]ug|[Hh]otfix): .+ \([A-Z]+-[0-9]+(, *[A-Z]+-[0-9]+)*\)$'
+commit_message_file=$(echo "$commit_message_file" | tr -d '\r') # Remove carriage returns
+commit_message=$(head -n 1 "$commit_message_file")
 
-if [[ ! "$commit_message" =~ $valid_commit_regex ]]; then
-  echo "Error: Commit message must match agreed on format."
-  echo "Example. refactor: your commit summary (TI-12, TI-23)"
+if ! awk -v msg="$commit_message" '
+BEGIN {
+  pattern = "^(Refactor|Feature|Feat|Bugfix|Docs|Chore|Bug|Hotfix|refactor|feature|feat|bugfix|docs|chore|bug|hotfix): .+ \\([A-Z]+-[0-9]+(, [A-Z]+-[0-9]+)*\\)$"
+  if (msg ~ pattern) {
+    exit 0
+  } else {
+    exit 1
+  }
+}'; then
+  echo "❌ Error: Commit message must match format."
+  echo "   Example: refactor: some message (TI-123)"
   exit 1
 fi
-
-exit 0
